import "./runtime-storage.test.cjs";
import "./worker-d1.test.mjs";
import "./wallet.test.cjs";
import "./mobile-startup.test.cjs";
import "./map-picker.test.cjs";
import "./itinerary-scroll.test.cjs";
import "./osaka-map.test.cjs";
import "./next-clock.test.cjs";
import "./weather.test.cjs";
